Add execution duration
lambdaclass/game_backend pull request #46
Opened 2023-11-23 23:34 UTC by manucamejo

2023-11-24 14:13 UTC, mFragaBA commented
is there a PR in the [curse_of_myrra repo](https://github.com/lambdaclass/curse_of_myrra) updating the `messages.proto` file and the csharp related files?

2023-11-24 15:48 UTC, manucamejo commented
> is there a PR in the [curse_of_myrra repo](https://github.com/lambdaclass/curse_of_myrra) updating the `messages.proto` file and the csharp related files?

Yes, [here](https://github.com/lambdaclass/curse_of_myrra/pull/1191)

2023-11-27 14:20 UTC, ncontinanza submitted a review, later dismissed
LGTM!

2023-11-27 14:24 UTC, mFragaBA requested changes

2023-11-27 16:07 UTC, mFragaBA commented on messages.proto
we talked about this and will discuss with @AminArria but it shouldn't block the merge of this PR. We'll iterate on a later PR

2023-11-27 16:12 UTC, mFragaBA approved these changes
LGTM!

2023-11-27 21:56 UTC, merged