Fix bot attack range and add randomness to it
lambdaclass/game_backend pull request #87
Opened 2023-12-05 22:42 UTC by agustinesco

The bots are walking on top of the enemies instead of attacking them when they're in range, this is due to two factors:
1. The :attack action is being updated every 500ms so if the bot started walking to an enemy he will continue to do so for 500 ms in the worst case scenario
2. The attack range is hardcoded in the `skill_would_hit/2` function, so we need to get the range value from the skills in the config file

2023-12-21 21:26 UTC, ncontinanza requested changes
The code seems fine, but during the game play I felt that the bots are not aggresive at all, ignoring me and the other bots and almost never attacking.

2023-12-22 12:30 UTC, AminArria commented
@agustinesco same experience, the bots basically did not attack me

2023-12-22 18:10 UTC, ncontinanza approved these changes

2023-12-22 19:18 UTC, manucamejo approved these changes

2023-12-22 19:18 UTC, merged